input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json { source => "message" }
  }
  mutate { add_field => { "environment" => "${ENV}" }}
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "hostel-system-logs-%{+YYYY.MM.dd}"
  }
}
